"""initial schema

Revision ID: 881ba76546b8
Revises: 0001_pgvector
Create Date: 2026-05-29 23:52:27.418620
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Custom column types referenced in this migration.
import pgvector.sqlalchemy.vector
import app.core.encryption

# revision identifiers, used by Alembic.
revision: str = '881ba76546b8'
down_revision: str | None = '0001_pgvector'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_chunks',
    sa.Column('content_type', sa.Enum('country', 'faq', 'sector_guide', 'project_summary', 'platform_doc', name='knowledge_content_type'), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('section', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_chunks'))
    )
    op.create_index('ix_knowledge_chunks_content_type_section', 'knowledge_chunks', ['content_type', 'section'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_country_code'), 'knowledge_chunks', ['country_code'], unique=False)
    op.create_table('users',
    sa.Column('clerk_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('role', sa.Enum('investor', 'project_owner', 'admin', name='user_role'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'suspended', name='user_status'), nullable=False),
    sa.Column('locale', sa.Enum('en', 'fr', 'zh', name='locale'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_clerk_id'), 'users', ['clerk_id'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_table('audit_log',
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.Uuid(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_log_actor_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_actor_user_id'), 'audit_log', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_target_type'), 'audit_log', ['target_type'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('session_token', sa.String(length=255), nullable=False),
    sa.Column('messages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_chat_sessions_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_sessions'))
    )
    op.create_index(op.f('ix_chat_sessions_session_token'), 'chat_sessions', ['session_token'], unique=True)
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_table('consultant_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('expertise_areas', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('sectors_served', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('years_of_experience', sa.Integer(), nullable=True),
    sa.Column('languages_spoken', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('key_achievements', sa.Text(), nullable=True),
    sa.Column('contact_preference', sa.Enum('email', 'platform_message', name='contact_preference'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'suspended', name='consultant_status'), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('documents', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_consultant_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consultant_profiles'))
    )
    op.create_index(op.f('ix_consultant_profiles_country'), 'consultant_profiles', ['country'], unique=False)
    op.create_index(op.f('ix_consultant_profiles_status'), 'consultant_profiles', ['status'], unique=False)
    op.create_index(op.f('ix_consultant_profiles_user_id'), 'consultant_profiles', ['user_id'], unique=True)
    op.create_table('country_content',
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('country_name', sa.String(length=128), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('investment_climate', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('investment_laws', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tax_system', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('business_registration', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('licensing_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('foreign_ownership_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('repatriation_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('immigration_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('key_contacts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recent_news', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['last_updated_by'], ['users.id'], name=op.f('fk_country_content_last_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_country_content'))
    )
    op.create_index(op.f('ix_country_content_country_code'), 'country_content', ['country_code'], unique=True)
    op.create_index(op.f('ix_country_content_is_published'), 'country_content', ['is_published'], unique=False)
    op.create_index(op.f('ix_country_content_region'), 'country_content', ['region'], unique=False)
    op.create_table('country_content_versions',
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('edited_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['edited_by'], ['users.id'], name=op.f('fk_country_content_versions_edited_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_country_content_versions'))
    )
    op.create_index(op.f('ix_country_content_versions_country_code'), 'country_content_versions', ['country_code'], unique=False)
    op.create_table('homepage_content',
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('process_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sector_highlights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('partner_logos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('team_members', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('advisory_board', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_homepage_content_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_homepage_content'))
    )
    op.create_table('investor_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('country_of_registration', sa.String(length=2), nullable=False),
    sa.Column('registration_number', app.core.encryption.EncryptedString(length=512), nullable=True),
    sa.Column('years_of_operation', sa.Integer(), nullable=True),
    sa.Column('registered_address', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=512), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_title', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=320), nullable=True),
    sa.Column('contact_phone', sa.String(length=64), nullable=True),
    sa.Column('investment_countries', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('investment_sectors', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('investment_types', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('min_ticket_size', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('max_ticket_size', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('preferred_deal_size', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('capital_availability', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('risk_appetite', sa.Enum('low', 'medium', 'high', name='risk_level'), nullable=True),
    sa.Column('target_roi_min', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('target_roi_max', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('time_horizon', sa.String(length=128), nullable=True),
    sa.Column('preferred_ownership_structures', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('exit_strategy', sa.String(length=255), nullable=True),
    sa.Column('preferred_ownership_pct_min', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('preferred_ownership_pct_max', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('esg_requirements', sa.Text(), nullable=True),
    sa.Column('sectors_excluded', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('political_risk_tolerance', sa.String(length=64), nullable=True),
    sa.Column('currency_risk_tolerance', sa.String(length=64), nullable=True),
    sa.Column('previous_projects', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('certifications', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('documents', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_investor_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investor_profiles'))
    )
    op.create_index(op.f('ix_investor_profiles_user_id'), 'investor_profiles', ['user_id'], unique=True)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=512), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('projects',
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('sector', sa.String(length=64), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('brief_description', sa.String(length=500), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=True),
    sa.Column('full_description', sa.Text(), nullable=True),
    sa.Column('project_stage', sa.Enum('concept', 'pre_revenue', 'revenue_generating', 'expansion', name='project_stage'), nullable=False),
    sa.Column('funding_required', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('funding_type', sa.Enum('equity', 'debt', 'jv', 'ppp', 'acquisition', name='funding_type'), nullable=False),
    sa.Column('min_investment', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('existing_funding', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('use_of_funds', sa.Text(), nullable=True),
    sa.Column('expected_roi_min', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('expected_roi_max', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('timeline_to_returns_months', sa.Integer(), nullable=True),
    sa.Column('projected_revenue_12m', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('projected_revenue_24m', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('projected_revenue_36m', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('current_annual_revenue', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('risk_level', sa.Enum('low', 'medium', 'high', name='risk_level'), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'suspended', name='project_status'), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('documents', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_projects_owner_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_index(op.f('ix_projects_country'), 'projects', ['country'], unique=False)
    op.create_index(op.f('ix_projects_is_featured'), 'projects', ['is_featured'], unique=False)
    op.create_index(op.f('ix_projects_owner_user_id'), 'projects', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_projects_sector'), 'projects', ['sector'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_index(op.f('ix_projects_title'), 'projects', ['title'], unique=False)
    op.create_table('consultant_matches',
    sa.Column('investor_id', sa.UUID(), nullable=False),
    sa.Column('consultant_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('recommended', 'viewed', 'contacted', 'engaged', 'dismissed', name='consultant_match_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['consultant_id'], ['consultant_profiles.id'], name=op.f('fk_consultant_matches_consultant_id_consultant_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['investor_id'], ['investor_profiles.id'], name=op.f('fk_consultant_matches_investor_id_investor_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_consultant_matches_project_id_projects'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consultant_matches'))
    )
    op.create_index(op.f('ix_consultant_matches_consultant_id'), 'consultant_matches', ['consultant_id'], unique=False)
    op.create_index(op.f('ix_consultant_matches_investor_id'), 'consultant_matches', ['investor_id'], unique=False)
    op.create_index(op.f('ix_consultant_matches_project_id'), 'consultant_matches', ['project_id'], unique=False)
    op.create_table('matches',
    sa.Column('investor_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('ai_generated', 'admin_manual', name='match_source'), nullable=False),
    sa.Column('status', sa.Enum('ai_recommended', 'admin_reviewed', 'investor_notified', 'investor_interested', 'nda_sent', 'nda_signed', 'confidential', 'mou_drafted', 'mou_signed', 'in_negotiation', 'due_diligence', 'closed_won', 'closed_lost', 'dismissed', name='match_status'), nullable=False),
    sa.Column('is_confidential', sa.Boolean(), nullable=False),
    sa.Column('investor_interest_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('admin_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investor_id'], ['investor_profiles.id'], name=op.f('fk_matches_investor_id_investor_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_matches_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matches')),
    sa.UniqueConstraint('investor_id', 'project_id', name='uq_matches_investor_project')
    )
    op.create_index(op.f('ix_matches_investor_id'), 'matches', ['investor_id'], unique=False)
    op.create_index(op.f('ix_matches_project_id'), 'matches', ['project_id'], unique=False)
    op.create_index(op.f('ix_matches_status'), 'matches', ['status'], unique=False)
    op.create_table('due_diligence_requests',
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('assigned_advisor_id', sa.UUID(), nullable=True),
    sa.Column('checklist', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('requested', 'in_progress', 'completed', name='due_diligence_status'), nullable=False),
    sa.Column('report_r2_key', sa.String(length=512), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_advisor_id'], ['users.id'], name=op.f('fk_due_diligence_requests_assigned_advisor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_due_diligence_requests_match_id_matches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_due_diligence_requests'))
    )
    op.create_index(op.f('ix_due_diligence_requests_assigned_advisor_id'), 'due_diligence_requests', ['assigned_advisor_id'], unique=False)
    op.create_index(op.f('ix_due_diligence_requests_match_id'), 'due_diligence_requests', ['match_id'], unique=True)
    op.create_table('milestones',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', 'overdue', name='milestone_status'), nullable=False),
    sa.Column('evidence_r2_key', sa.String(length=512), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_milestones_match_id_matches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_milestones_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_milestones'))
    )
    op.create_index(op.f('ix_milestones_match_id'), 'milestones', ['match_id'], unique=False)
    op.create_index(op.f('ix_milestones_project_id'), 'milestones', ['project_id'], unique=False)
    # ### end Alembic commands ###

    # HNSW indexes for pgvector cosine similarity search (PRD §8.3, §12).
    # Added manually — Alembic autogenerate does not emit vector indexes.
    for table in ("investor_profiles", "projects", "consultant_profiles", "knowledge_chunks"):
        op.create_index(
            f"ix_{table}_embedding_hnsw",
            table,
            ["embedding"],
            unique=False,
            postgresql_using="hnsw",
            postgresql_with={"m": 16, "ef_construction": 64},
            postgresql_ops={"embedding": "vector_cosine_ops"},
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for table in ("investor_profiles", "projects", "consultant_profiles", "knowledge_chunks"):
        op.drop_index(f"ix_{table}_embedding_hnsw", table_name=table)
    op.drop_index(op.f('ix_milestones_project_id'), table_name='milestones')
    op.drop_index(op.f('ix_milestones_match_id'), table_name='milestones')
    op.drop_table('milestones')
    op.drop_index(op.f('ix_due_diligence_requests_match_id'), table_name='due_diligence_requests')
    op.drop_index(op.f('ix_due_diligence_requests_assigned_advisor_id'), table_name='due_diligence_requests')
    op.drop_table('due_diligence_requests')
    op.drop_index(op.f('ix_matches_status'), table_name='matches')
    op.drop_index(op.f('ix_matches_project_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_investor_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_consultant_matches_project_id'), table_name='consultant_matches')
    op.drop_index(op.f('ix_consultant_matches_investor_id'), table_name='consultant_matches')
    op.drop_index(op.f('ix_consultant_matches_consultant_id'), table_name='consultant_matches')
    op.drop_table('consultant_matches')
    op.drop_index(op.f('ix_projects_title'), table_name='projects')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_sector'), table_name='projects')
    op.drop_index(op.f('ix_projects_owner_user_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_is_featured'), table_name='projects')
    op.drop_index(op.f('ix_projects_country'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_investor_profiles_user_id'), table_name='investor_profiles')
    op.drop_table('investor_profiles')
    op.drop_table('homepage_content')
    op.drop_index(op.f('ix_country_content_versions_country_code'), table_name='country_content_versions')
    op.drop_table('country_content_versions')
    op.drop_index(op.f('ix_country_content_region'), table_name='country_content')
    op.drop_index(op.f('ix_country_content_is_published'), table_name='country_content')
    op.drop_index(op.f('ix_country_content_country_code'), table_name='country_content')
    op.drop_table('country_content')
    op.drop_index(op.f('ix_consultant_profiles_user_id'), table_name='consultant_profiles')
    op.drop_index(op.f('ix_consultant_profiles_status'), table_name='consultant_profiles')
    op.drop_index(op.f('ix_consultant_profiles_country'), table_name='consultant_profiles')
    op.drop_table('consultant_profiles')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_session_token'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_audit_log_target_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_clerk_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_knowledge_chunks_country_code'), table_name='knowledge_chunks')
    op.drop_index('ix_knowledge_chunks_content_type_section', table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    # ### end Alembic commands ###

    # Drop native enum types (autogenerate does not remove these on table drop,
    # which otherwise breaks a downgrade→upgrade round-trip).
    for enum_name in (
        "knowledge_content_type",
        "milestone_status",
        "due_diligence_status",
        "match_status",
        "match_source",
        "consultant_match_status",
        "project_status",
        "funding_type",
        "project_stage",
        "risk_level",
        "consultant_status",
        "contact_preference",
        "locale",
        "user_status",
        "user_role",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
